#!/bin/bash

# Check for root privileges
if [ "$EUID" -ne 0 ] || [ "$(id -u)" -ne 0 ]; then
    echo "Error: This script must be executed as root or with sudo."
    exit 1
fi

ARGS=$(env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY)
INSTALLER="/maloneyos/installer"

pkexec ${ARGS} python3 ${INSTALLER}/disks.py
pkexec ${ARGS} bash ${INSTALLER}/zfs.sh
pkexec ${ARGS} python3 ${INSTALLER}/squashfs.py
pkexec ${ARGS} bash ${INSTALLER}/chroot.sh
pkexec ${ARGS} python3 ${INSTALLER}/makeinitcpio.py
pkexec ${ARGS} bash ${INSTALLER}/bootloader.sh
pkexec ${ARGS} bash ${INSTALLER}/user.sh
pkexec ${ARGS} bash ${INSTALLER}/cleanup.sh
pkexec ${ARGS} bash ${INSTALLER}/finalize.py