#!/bin/bash

# Check for root privileges
if [ "$EUID" -eq 0 ] || [ "$(id -u)" -eq 0 ]; then
    echo "Error: This script cannot be executed as root or with sudo."
    exit 1
fi

python3 /maloneyos/installer/disks.py
pkexec /maloneyos/installer/disks.py/01-zfs.sh
pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY python3 /maloneyos/installer/02-extractsfs.py